spring.application.name=sdg-notification
# Server
server.port=8080

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true

# SSE emitter
sse.emitter.timeout-ms=300000

# Hybrid Dispatcher
hybrid.dispatcher.broker-threshold=100
hybrid.dispatcher.hysteresis=10
hybrid.dispatcher.transition-buffer-ms=50

# Logging
logging.level.com.omarelassal.sdgnotification=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs